services:
  dev-env:
    # Use 'image' and 'build' options if changes in image are necessary or the
    # build speed is higher than the download speed
    #image: yocto-buildcontainer
    #build: docker
    # Use 'image' to download directly from registry
    image: ghcr.io/thomas187/yocto-buildcontainer-14.04/thomas187/yocto-buildcontainer-14.04:latest
    volumes:
      - ./workspace:/home/dev/workspace
    environment:
      - DISPLAY=$DISPLAY
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
